"use client";

import { useEffect, useState } from "react";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { cctvApi, CAMERA_BRANDS, type PublicCamera } from "@/lib/cctv-api";

const empty = { id: "", name: "", description: "", brand: "", host: "", rtsp_port: 8554, rtsp_url: "", username: "", password: "", onvif_port: 8000, ptz_profile: "" };

export function CameraDialog({
  open,
  onOpenChange,
  onSaved,
  camera,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  onSaved: () => void;
  camera?: PublicCamera | null;
}) {
  const editing = !!camera;
  const [form, setForm] = useState(empty);
  const [msg, setMsg] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (open) {
      setMsg("");
      setForm(
        camera
          ? {
              id: camera.id,
              name: camera.name ?? "",
              description: camera.description ?? "",
              host: camera.host ?? "",
              rtsp_port: camera.rtsp_port || 8554,
              rtsp_url: "",
              username: camera.username ?? "",
              password: "",
              onvif_port: camera.onvif_port || 8000,
              ptz_profile: camera.ptz_profile ?? "",
              brand: camera.brand ?? "",
            }
          : empty,
      );
    }
  }, [open, camera]);

  function set(k: string, v: string | number) {
    setForm((f) => ({ ...f, [k]: v }));
  }

  function close(v: boolean) {
    if (!saving) onOpenChange(v);
  }

  async function submit() {
    setMsg("");
    // id is auto-generated by the backend (cam1, cam2, ...) on create
    if (!form.name.trim()) {
      setMsg("Name is required.");
      return;
    }
    if (!editing) {
      // backend Create requires a full rtsp:// URL
      if (!form.rtsp_url.trim().toLowerCase().startsWith("rtsp://")) {
        setMsg("A full RTSP URL starting with rtsp:// is required.");
        return;
      }
    }
    setSaving(true);
    try {
      if (editing && camera) {
        await cctvApi.updateCamera(camera.id, { ...form, id: camera.id });
      } else {
        // no id: backend auto-assigns cam1, cam2, ...
        await cctvApi.createCamera({
          name: form.name,
          description: form.description,
          host: form.host,
          rtsp_port: form.rtsp_port,
          rtsp_url: form.rtsp_url,
          username: form.username,
          password: form.password,
          onvif_port: form.onvif_port,
          ptz_profile: form.ptz_profile,
          brand: form.brand,
        });
      }
      try {
        await cctvApi.go2rtcSync();
      } catch {
        // non-fatal: change is saved, stream registers on next sync/restart
      }
      onOpenChange(false);
      onSaved();
    } catch (e) {
      setMsg(e instanceof Error ? e.message : "Failed to save camera.");
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={close}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-[560px]">
        <DialogHeader>
          <DialogTitle>{editing ? `Edit Camera ${camera?.id}` : "Add Camera"}</DialogTitle>
        </DialogHeader>
        <div className="grid grid-cols-2 gap-3">
          {editing ? (
            <p className="col-span-2 text-xs text-muted-foreground">
              Camera ID: <span className="font-mono font-semibold text-foreground">{camera?.id}</span> (auto-assigned, cannot be changed)
            </p>
          ) : null}
          <label htmlFor="cam-name" className="col-span-2 flex flex-col gap-1 text-xs">
            Name *
            <Input id="cam-name" value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="Cam 2" />
          </label>
          <label htmlFor="cam-desc" className="col-span-2 flex flex-col gap-1 text-xs">
            Description
            <Input id="cam-desc" value={form.description} onChange={(e) => set("description", e.target.value)} placeholder="Lobby entrance" />
          </label>
          <label htmlFor="cam-host" className="flex flex-col gap-1 text-xs">
            Host
            <Input id="cam-host" value={form.host} onChange={(e) => set("host", e.target.value)} placeholder="10.10.11.20" />
          </label>
          <label htmlFor="cam-rtsp-port" className="flex flex-col gap-1 text-xs">
            RTSP Port
            <Input id="cam-rtsp-port" type="number" value={form.rtsp_port} onChange={(e) => set("rtsp_port", Number(e.target.value))} />
          </label>
          <label htmlFor="cam-rtsp-url" className="col-span-2 flex flex-col gap-1 text-xs">
            RTSP URL {editing ? "(blank = keep existing)" : "(full, required)"}
            <Input
              id="cam-rtsp-url"
              value={form.rtsp_url as string}
              onChange={(e) => set("rtsp_url", e.target.value)}
              placeholder={editing ? "Leave blank to keep existing" : "rtsp://user:pass@host:8554/Streaming/Channels/101"}
            />
          </label>
          <label htmlFor="cam-user" className="flex flex-col gap-1 text-xs">
            Username
            <Input id="cam-user" value={form.username} onChange={(e) => set("username", e.target.value)} placeholder="admin" />
          </label>
          <label htmlFor="cam-pass" className="flex flex-col gap-1 text-xs">
            Password {editing ? "(blank = keep existing)" : ""}
            <Input
              id="cam-pass"
              type="password"
              value={form.password as string}
              onChange={(e) => set("password", e.target.value)}
              placeholder={editing ? "Leave blank to keep existing" : "••••••••"}
            />
          </label>
          <label htmlFor="cam-onvif-port" className="flex flex-col gap-1 text-xs">
            ONVIF Port
            <Input id="cam-onvif-port" type="number" value={form.onvif_port} onChange={(e) => set("onvif_port", Number(e.target.value))} />
          </label>
          <label htmlFor="cam-brand" className="flex flex-col gap-1 text-xs">
            Brand
            <select
              id="cam-brand"
              value={form.brand as string}
              onChange={(e) => {
                const v = e.target.value;
                const preset = CAMERA_BRANDS.find((b) => b.value === v)?.ptz_profile ?? "";
                // brand preset auto-fills the token; Generic leaves the field untouched
                setForm((f) => ({ ...f, brand: v, ptz_profile: preset || f.ptz_profile }));
              }}
              className="rounded border bg-background px-2 py-1.5 text-sm"
            >
              {CAMERA_BRANDS.map((b) => (
                <option key={b.value || "generic"} value={b.value}>
                  {b.label}
                </option>
              ))}
            </select>
          </label>
          <label htmlFor="cam-ptz-profile" className="flex flex-col gap-1 text-xs">
            PTZ Profile (blank = auto)
            <Input
              id="cam-ptz-profile"
              value={form.ptz_profile as string}
              onChange={(e) => set("ptz_profile", e.target.value)}
              placeholder="e.g. IPCProfilesToken0"
            />
          </label>
        </div>
        {msg ? <p className="text-sm text-amber-500">{msg}</p> : null}
        <DialogFooter>
          <Button variant="outline" onClick={() => close(false)} disabled={saving}>
            Cancel
          </Button>
          <Button onClick={submit} disabled={saving}>
            {saving ? "Saving…" : editing ? "Save Changes" : "Add Camera"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
